### ISSUE TITLE
Nested apps

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#12]
The viewer seems to be having some trouble with nested apps. See 2.63, for example. 

The code is `<l n="63"><app>
                                <lem>saepe cadit festis <app>
                                        <lem>devota</lem>
                                        <rdg wit="#Gryph.">devecta</rdg>
                                    </app>
                                    <app>
                                        <lem wit="#P #ζ2 #p" source="#h #Martell. #Kempfer #Baehr. #Schenkl">Parilibus</lem>
                                        <rdg wit="#G #N">paliribus</rdg>
                                        <rdg wit="#V" source="#edd.">palilibus</rdg>
                                    </app> agna.</lem>
                                <rdg wit="#ε #e #d #c #Nordh.">perfundens aras divorum sanguine
                                    largo</rdg>
                            </app></l>`

The viewer is treating the readings on the same level.

**Comment by hcayless** [comment]
Not quite fixed in 7121795, but improved. Nested app info is now repeated. Also not sure this is quite the right way to encode that entry, but this is a legitimate issue, so I'd like to fix it before fixing the markup.

**Comment by sjhuskey** [comment]
See also 3.18. Lots of nesting. Perhaps it should be encoded differently, but I'm not sure how to represent it.

Code: `<app>
                                <lem><app>
                                        <lem wit="#N #G" source="#Schenkl">quavis</lem>
                                        <rdg wit="#P #V" source="#edd.">quamvis</rdg>
                                    </app>
                                    <app>
                                        <lem wit="#N #G #ρ #φ #ε #α #λ #π #δ #μ #η #d" source="#n #Barth #Ulit.">contentus</lem>
                                        <rdg wit="#N #ρ">contetus</rdg>
                                        <rdg source="#Burm.">contendis</rdg>
                                        <rdg wit="#P #γ #κ #χ #ν #β #ρ2" source="#edd.">contemptus</rdg>
                                    </app>
                                    <app>
                                        <lem>abibo</lem>
                                        <rdg wit="#P">adhibo</rdg>
                                    </app></lem>
                                <rdg source="#Leo #Fritzsche" xml:id="rdg3.18quamvis">quamvis
                                    contemptus adibo</rdg>
                                <note target="rdg3.18quamvis">Leo (l.l. p. 617) Fritzche (De Calp.
                                    ecl. I–III Schwerin 1903 p.14)</note>
                            </app>`

**Comment by hcayless** [comment]
Should be fixed
