### ISSUE TITLE
corrLineOm

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#14]
φ omits lines 2.73-75, but then φ2 adds them. We handled that line by line, adding a `<rdgGrp>` in an `<app>` with a `<lem>` that spans the text of the line, but inside of  `<l> </l>`. I think later on we went to wrapping the whole line or groups of lines in the app. Anyway, the viewer shows _om. φ φ_, but it should be something like om. φ (add. φ2).

**Comment by sjhuskey** [comment]
I noticed that I did not specify φ2 in the wit, but indicated φ2 in the @hand inside <add>. That seems a bad decision now. Do you agree?

**Comment by hcayless** [comment]
Yeah, I think we've decided to move away from using `@hand` in favor of describing hands as witnesses.

**Comment by hcayless** [comment]
Fixed in d6dbb275b312c6081731d1e9f34626767d931565
