### ISSUE TITLE
Nested app not showing

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#17]
Line 1.3 is omitted in κ and χ, so the line is enclosed in an `<app>` with `@type` "lineOmission". The line is the `<lem>` and the omission is the `<rdg>`. There's also an `<app>` in the line for `<lem>` musta. The reader has a question mark indicator for both `<app>` elements, but the one for musta doesn't do anything that I can detect.

**Comment by hcayless** [comment]
What I'm noticing is that it works initially, but stops working if you switch off line 3 and then switch it back on again. It's losing the event listeners that trigger the mouseover and the app dialog in that case.

**Comment by hcayless** [comment]
Nested apps should now keep their functionality after being switched off and then back on.
