### ISSUE TITLE
Word swapping not functional

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#18]
At line 1.8–9, the words ista and antra are swapped in different mss. We handled that with this: `<app type="transposition">
                                <lem wit="#N #G" source="#GlaeserSqq" xml:id="l8a1lem1" exclude="l9a1rdg1">antra</lem>
                                <rdg wit="#P #V" source="#eddAnteGlaeser" xml:id="l8a1rdg1" exclude="l9a1lem1">ista</rdg>
                            </app> petamus</l>
                        <l n="9"><app type="transposition">
                                <lem wit="#N #G" source="#GlaeserSqq" xml:id="l9a1lem1" exclude="#l8a1rdg1">ista</lem>
                                <rdg wit="#P #V" source="#eddAnteGlaeser" xml:id="l9a1rdg1" exclude="l8a1lem1">antra</rdg>
                            </app>`

The viewer is not swapping the variants.

**Comment by hcayless** [comment]
I think this is a use case for the new `@require` attribute (see https://github.com/TEIC/TEI/issues/1418). I could go ahead and add it to our ODD in advance of the next TEI release.

**Comment by sjhuskey** [comment]
That seems like a good idea.

**Comment by hcayless** [comment]
Fixed. Use `@require` if this functionality is needed.
