### ISSUE TITLE
Need a better way to include links in <app>

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#19]
In some cases where Giarratano cites a specific page number in a source and that source is available online, I have used `<ptr>` in a `<note>` to point to the URL for the page, but it's not great to look at in the viewer, since it just prints the entire URL, which can be very, very long. Is there a better alternative?

**Comment by hcayless** [comment]
We can truncate the `<ptr>`'s target URL for display (maybe just show the domain), or use `<ref>` instead, which works like an HTML link.

**Comment by sjhuskey** [comment]
I think it's preferable to use `<ref>`. I'll work on replacing `<ptr>` with `<ref>` now.

**Comment by sjhuskey** [comment]
Updated editio.xml so that `ptr` has been replaced with `ref`.
