### ISSUE TITLE
Paleographical details not being displayed

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#20]
At Calp. 2.10, G adds the correct reading above the line: `<app>
                            <lem xml:id="lem2.11.10">pecudum</lem>
                            <rdgGrp type="anteCorr">
                                <rdg wit="#G" varSeq="1" xml:id="rdgPecorum">pecorum</rdg>
                                <rdg wit="#G" varSeq="2"><add place="above" copyOf="#lem2.11.10"/></rdg>
                            </rdgGrp>
                            <witDetail wit="#G" target="#rdgPecorum">quod def. <ref target="#Mueller">L. Mueller</ref> (l. l. p. 1071)</witDetail>
                        </app>`
The reader is displaying only the variant reading and (corr. G.). The witDetail is also missing from the display.

**Comment by hcayless** [comment]
The witDetail issue was that it was assuming witDetail would be a sibling of the rdg. I've fixed that. If we want more detail on the corrections, I'll need to produce a mapping from the `add` types to the language we want to display. G. has "corr. supr. lin." here. What else would we want to see? "Corr. marg." presumably; just "corr." if it's inline. Or, we could use `wit` to encode the notes about the correction:

``` xml
<app> 
  <lem xml:id="lem2.11.10">pecudum</lem> 
  <rdgGrp type="anteCorr"> 
    <rdg wit="#G" varSeq="1" xml:id="rdgPecorum">pecorum</rdg> 
    <rdg wit="#G" varSeq="2"><add place="above" copyOf="#lem2.11.10"/></rdg>
    <wit>(corr. supr. lin.)</wit>
  </rdgGrp> 
  <witDetail wit="#G" target="#rdgPecorum">quod def. <ref target="#Mueller">L. Mueller</ref> (l. l. p. 1071)</witDetail> 
</app>
```

That's kind of redundant though...

**Comment by hcayless** [comment]
Here's the list of rdgGrp `@type`s right now. Errors aside, we could use this to manage what kind of message is displayed in the app. crit. We could also surface the correction itself instead. I could render the example as:

pecorum G corr. `pecudum´ 

for example (see the EpiDoc for handling additions, http://www.stoa.org/epidoc/gl/latest/trans-addition.html).

anteCorr
corrOmission
edCorr
conjecture
 mutation
MSVariants
corrMargin
 marginalia
corrOm
corrMarg
subvariant
subvariants
corrLineOm
correction
contjectures
SubVariants
multiVariants
multiReadings
subVariants
postCorr
multivariants

**Comment by sjhuskey** [comment]
Yeah, a lot of those could winnowed out, I think. I'll take a closer look
when I have a computer in front of me.

Sam

**Comment by sjhuskey** [comment]
I have removed nearly all of the `@type`s on rdgGrp and switched everything over to the new way of dealing with corrections. The `witDetail` for 2.10 is still not showing up, at least for the correction-altered one. On the positive side, self-closing `witDetail` elements are behaving as expected, i.e., with (a.c.) and (p.c.) inserted where they should be. The problem, I guess is with `witDetail` when it has content.
