### ISSUE TITLE
App. Icons not displaying correctly for poetry 

### ISSUE THREAD

**Issue by sjhuskey** [DigitalLatin/viewer#28]
The icons for apparatus criticus material are appearing only one per line in poetry. I think this has to do with what was done for viewing prose texts. Since both BAlex and Calp. are often used for demo purposes, fixing this seems like a high priority.

**Comment by hcayless** [comment]
Since we have BAlex now too, I moved Calpurnius to https://digitallatin.github.io/viewer/calpurnius.html. I thought I'd copied that version over to editio.html, but I must have either neglected to push it or messed something up. Will fix.

**Comment by hcayless** [comment]
Fixed.
